#!/usr/bin/env bash

set -eu

auth="${ZENDESK_AUTH:-fred:password}"

http \
  --verbose \
  --auth "${auth}" \
  POST :8080/tickets.json \
  'Content-Type:application/json' \
  'Accept:application/json' \
  <<!
{
  "ticket": {
    "subject": "A subject",
    "comment": {
      "body": "A comment."
    }
  }
}
!
