#!/usr/bin/env bash

set -eu

subdomain="${ZENDESK_SUBDOMAIN}"
username="${ZENDESK_USERNAME}"
password="${ZENDESK_PASSWORD}"

http --verbose \
  --auth "${username}:${password}" \
  POST "https://${subdomain}.zendesk.com/api/v2/tickets.json" \
  'Content-Type:application/json' \
  'Accept:application/json' \
  "$@" \
  <<!
{
  "ticket": {
    "requester": {
      "name": "Wilma Flintstone",
      "email": "steven+wilma@steshaw.org"
    },
    "subject": "Awesome Company - Trial",
    "comment": {
      "html_body": "Wilma Flintstone has joined from <b>Awesome Company</b>.",
      "public": false
    }
  }
}
!
