#!/usr/bin/env bash

set -eu

subdomain="${ZENDESK_SUBDOMAIN}"
username="${ZENDESK_USERNAME}"
password="${ZENDESK_PASSWORD}"

http \
  --auth "${username}:${password}" \
  POST "https://${subdomain}.zendesk.com/api/v2/tickets.json" \
  'Content-Type:application/json' \
  'Accept:application/json' \
  "$@" \
  <<!
{
  "ticket": {
    "requester": {
      "name": "Wilma Flintstone",
      "email": "steven+wilma@steshaw.org"
    },
    "subject": "Awesome Jobs - Betterteam Trial",
    "comment": {
      "body": "Wilma Flintstone, steven+wilma@steshaw.org, Awesome Jobs"
    },
    "is_public": false
  }
}
!
