#!/usr/bin/env bash

set -eu

subdomain="${ZENDESK_SUBDOMAIN}"
email="${ZENDESK_EMAIL}"
password="${ZENDESK_PASSWORD}"

http \
  --auth "${email}:${password}" \
  GET "https://${subdomain}.zendesk.com/api/v2/tickets.json" \
  "Accept:application/json"
